version: '3.8'

services:
  eureka-server:
    build: . # Compiles the Eureka server Dockerfile in this directory
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - shared-network

networks:
  shared-network:
    external: true
    name: reckon-arc # Connects to the existing network