version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - app-network

  app:
    build: .
    container_name: user_authentication_service
    depends_on:
      - db
    ports:
      - "8083:8083"
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/auth_db
      # This routes perfectly to your standalone Eureka container on the reckon-arc network
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka/
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  app-network:
    external: true
    name: reckon-arc