version: '3.8'

services:
  eureka-server:
    image: your-eureka-image-name # Kendi imaj adınla değiştir
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - reckon-arc

  reckon-gateway:
    build: .
    container_name: reckon-gateway
    ports:
      - "8084:8084"
    networks:
      - reckon-arc
    depends_on:
      - eureka-server

  user-authentication-service:
    image: your-auth-image-name
    container_name: UserAuthenticationService
    networks:
      - reckon-arc
    depends_on:
      - eureka-server

  cold-wallet-manager-service:
    image: your-wallet-image-name
    container_name: Cold-Wallet-Manager-Service
    networks:
      - reckon-arc
    depends_on:
      - eureka-server

# reckon-arc network'ünü burada tanımlıyoruz
networks:
  reckon-arc:
    # Eğer bu network'ü terminalden 'docker network create reckon-arc' diyerek 
    # manuel oluşturduysan 'external: true' yapmalısın. 
    # Eğer docker-compose'un kendisinin oluşturmasını istiyorsan 'driver: bridge' kullanabilirsin.
    external: true