#
services:
  # ----------------------------------------------------
  # Your Spring Boot Service (hiveos-integration)
  # ----------------------------------------------------
  hiveos-app:
    # If you have a Dockerfile locally, you can use:
    build: .
    # Or if you already have the image pulled/built:
    # image: hiveos-integration:latest
    ports:
      - "8088:8080"
    environment:
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin123

    networks:
      - reckon-ext-net
    volumes:
      # We mount the shared volume to the default relative path inside the container where Spring Boot writes 'logs'
      - app-logs:/app/logs

  # Filebeat has been removed as it is now handled centrally by log-manager.

volumes:
  # Define the shared volume
  app-logs:
    external: true
    name: reckon-app-logs


networks:
  reckon-ext-net:
    external: true
    name: reckon-ext-net
